import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import axios from 'axios';
import { RootState, AppThunk } from '../../redux/store';
import { fetchCount } from './counterAPI';
import { Action, Juego } from '../../utils/interfaces'
export interface GamesState {
  value: number;
  listGames : Juego[]
  status: 'idle' | 'loading' | 'failed'| 'succeded';
}

const initialState: GamesState = {
  value: 0,
  listGames :[],
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getAllGames = createAsyncThunk(
  'games/getAllGames',
  async () => {
    const response = await axios.get('https://www.freetogame.com/api/games')
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const GameSlice = createSlice({
  name: 'games',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
     builder
       .addCase(getAllGames.pending, (state) => {
         state.status = 'loading';
       })
       .addCase(getAllGames.fulfilled, (state, action: any) => {
         state.status = 'succeded';
        state.listGames = action.payload;
       });
  },
});


export default GameSlice.reducer;
